<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PQ.4aEU' shared service.

return $this->privates['.service_locator.PQ.4aEU'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('ticket' => function (): \App\Entity\Ticket {
    return ($this->privates['.errored..service_locator.PQ.4aEU.App\Entity\Ticket'] ?? $this->load('getTicketService.php'));
}));
