<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.D3yEvxt' shared service.

return $this->privates['.service_locator.D3yEvxt'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('error' => function (): \App\Service\error {
    return ($this->privates['App\Service\error'] ?? $this->privates['App\Service\error'] = new \App\Service\error());
}, 'requestflash' => function (): \App\Service\requestflash {
    return ($this->privates['App\Service\requestflash'] ?? $this->privates['App\Service\requestflash'] = new \App\Service\requestflash());
}));
