<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Fjh.aNU' shared service.

return $this->privates['.service_locator.Fjh.aNU'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('requestflash' => function (): \App\Service\requestflash {
    return ($this->privates['App\Service\requestflash'] ?? $this->privates['App\Service\requestflash'] = new \App\Service\requestflash());
}));
