<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\HomeController::home' => function () {
    return ($this->privates['.service_locator.vI0u2rX'] ?? $this->load('get_ServiceLocator_VI0u2rXService.php'));
}, 'App\\Controller\\IntervencionController::Actualizar' => function () {
    return ($this->privates['.service_locator.iVnz5A2'] ?? $this->load('get_ServiceLocator_IVnz5A2Service.php'));
}, 'App\\Controller\\IntervencionController::CerrarIntervencion' => function () {
    return ($this->privates['.service_locator.2gVA67F'] ?? $this->load('get_ServiceLocator_2gVA67FService.php'));
}, 'App\\Controller\\IntervencionController::Devolver' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\IntervencionController::PausarIntervencion' => function () {
    return ($this->privates['.service_locator.2gVA67F'] ?? $this->load('get_ServiceLocator_2gVA67FService.php'));
}, 'App\\Controller\\IntervencionController::RechazarIntervencion' => function () {
    return ($this->privates['.service_locator.2gVA67F'] ?? $this->load('get_ServiceLocator_2gVA67FService.php'));
}, 'App\\Controller\\IntervencionController::Terminar' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\IntervencionController::VistaActualizar' => function () {
    return ($this->privates['.service_locator.iVnz5A2'] ?? $this->load('get_ServiceLocator_IVnz5A2Service.php'));
}, 'App\\Controller\\IntervencionController::poseeIntervencionesAbiertas' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\RegistrationController::register' => function () {
    return ($this->privates['.service_locator.cPEJcDm'] ?? $this->load('get_ServiceLocator_CPEJcDmService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\TicketController::CU01CerrarMesa' => function () {
    return ($this->privates['.service_locator.D3yEvxt'] ?? $this->load('get_ServiceLocator_D3yEvxtService.php'));
}, 'App\\Controller\\TicketController::CU01DerivarMesa' => function () {
    return ($this->privates['.service_locator.D3yEvxt'] ?? $this->load('get_ServiceLocator_D3yEvxtService.php'));
}, 'App\\Controller\\TicketController::Consultar' => function () {
    return ($this->privates['.service_locator.D3yEvxt'] ?? $this->load('get_ServiceLocator_D3yEvxtService.php'));
}, 'App\\Controller\\TicketController::DerivarTicket' => function () {
    return ($this->privates['.service_locator.Fjh.aNU'] ?? $this->load('get_ServiceLocator_Fjh_ANUService.php'));
}, 'App\\Controller\\TicketController::Registrar' => function () {
    return ($this->privates['.service_locator.D3yEvxt'] ?? $this->load('get_ServiceLocator_D3yEvxtService.php'));
}, 'App\\Controller\\TicketController::VistaDerivarTicket' => function () {
    return ($this->privates['.service_locator.Fjh.aNU'] ?? $this->load('get_ServiceLocator_Fjh_ANUService.php'));
}, 'App\\Controller\\TicketController::VistaRegistrar' => function () {
    return ($this->privates['.service_locator.D3yEvxt'] ?? $this->load('get_ServiceLocator_D3yEvxtService.php'));
}, 'App\\Controller\\TicketController::buildDerivarDTO' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController::buildHistoricoDTO' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController::buildUsuarioDTO' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController::cerrarHistorialesTicket' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController::cerrarIntervencionMesa' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController::derivar' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController::getClasificacion' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController::getGrupoResolucion' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\HomeController:home' => function () {
    return ($this->privates['.service_locator.vI0u2rX'] ?? $this->load('get_ServiceLocator_VI0u2rXService.php'));
}, 'App\\Controller\\IntervencionController:Actualizar' => function () {
    return ($this->privates['.service_locator.iVnz5A2'] ?? $this->load('get_ServiceLocator_IVnz5A2Service.php'));
}, 'App\\Controller\\IntervencionController:CerrarIntervencion' => function () {
    return ($this->privates['.service_locator.2gVA67F'] ?? $this->load('get_ServiceLocator_2gVA67FService.php'));
}, 'App\\Controller\\IntervencionController:Devolver' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\IntervencionController:PausarIntervencion' => function () {
    return ($this->privates['.service_locator.2gVA67F'] ?? $this->load('get_ServiceLocator_2gVA67FService.php'));
}, 'App\\Controller\\IntervencionController:RechazarIntervencion' => function () {
    return ($this->privates['.service_locator.2gVA67F'] ?? $this->load('get_ServiceLocator_2gVA67FService.php'));
}, 'App\\Controller\\IntervencionController:Terminar' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\IntervencionController:VistaActualizar' => function () {
    return ($this->privates['.service_locator.iVnz5A2'] ?? $this->load('get_ServiceLocator_IVnz5A2Service.php'));
}, 'App\\Controller\\IntervencionController:poseeIntervencionesAbiertas' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\RegistrationController:register' => function () {
    return ($this->privates['.service_locator.cPEJcDm'] ?? $this->load('get_ServiceLocator_CPEJcDmService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\TicketController:CU01CerrarMesa' => function () {
    return ($this->privates['.service_locator.D3yEvxt'] ?? $this->load('get_ServiceLocator_D3yEvxtService.php'));
}, 'App\\Controller\\TicketController:CU01DerivarMesa' => function () {
    return ($this->privates['.service_locator.D3yEvxt'] ?? $this->load('get_ServiceLocator_D3yEvxtService.php'));
}, 'App\\Controller\\TicketController:Consultar' => function () {
    return ($this->privates['.service_locator.D3yEvxt'] ?? $this->load('get_ServiceLocator_D3yEvxtService.php'));
}, 'App\\Controller\\TicketController:DerivarTicket' => function () {
    return ($this->privates['.service_locator.Fjh.aNU'] ?? $this->load('get_ServiceLocator_Fjh_ANUService.php'));
}, 'App\\Controller\\TicketController:Registrar' => function () {
    return ($this->privates['.service_locator.D3yEvxt'] ?? $this->load('get_ServiceLocator_D3yEvxtService.php'));
}, 'App\\Controller\\TicketController:VistaDerivarTicket' => function () {
    return ($this->privates['.service_locator.Fjh.aNU'] ?? $this->load('get_ServiceLocator_Fjh_ANUService.php'));
}, 'App\\Controller\\TicketController:VistaRegistrar' => function () {
    return ($this->privates['.service_locator.D3yEvxt'] ?? $this->load('get_ServiceLocator_D3yEvxtService.php'));
}, 'App\\Controller\\TicketController:buildDerivarDTO' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController:buildHistoricoDTO' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController:buildUsuarioDTO' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController:cerrarHistorialesTicket' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController:cerrarIntervencionMesa' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController:derivar' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController:getClasificacion' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}, 'App\\Controller\\TicketController:getGrupoResolucion' => function () {
    return ($this->privates['.service_locator.PQ.4aEU'] ?? $this->load('get_ServiceLocator_PQ_4aEUService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
