<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.2gVA67F.App\Entity\Intervencion' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.2gVA67F": it references class "App\\Entity\\Intervencion" but no such service exists.');
