#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

register:
    path:       /register
    controller: App\Controller\RegistrationController::register

login:
    path:       /login
    controller: App\Controller\SecurityController::login

home:
    path:       /home
    controller: App\Controller\HomeController::home


logout:
    path:       /logout
    controller: App\Controller\SecurityController::logout




#---------------------------------------------------------------------------------------------------------------------#
#-------RUTAS PARA LA MESA DE AYUDA----------#
#---------------------------------------------------------------------------------------------------------------------#
CU01registrarTicket:
              path:     /CU01registrarTicket
              controller: App\Controller\TicketController::VistaRegistrar
              methods: [GET]

CU01ProcesarTicket:
              path:     /CU01registrarTicket
              controller: App\Controller\TicketController::Registrar
              methods: [POST]

CU01CerrarMesa:
              path:     /CU01AccionesRequeridasCerrar
              controller: App\Controller\TicketController::CU01CerrarMesa
              methods: [POST]


CU01DerivarMesa:
              path:     /CU01AccionesRequeridasDerivar
              controller: App\Controller\TicketController::CU01DerivarMesa
              methods: [POST]

CU02ConsultarTicket:
              path:     /CU02ConsultarTicket
              controller: App\Controller\TicketController::VistaConsultar
              methods: [GET]

CU02ProcesarConsulta:
              path:     /CU02ConsultarTicket
              controller: App\Controller\TicketController::Consultar
              methods: [POST]

CU02ConsultarTicket2:
              path:     /CU02ConsultarTicket2
              controller: App\Controller\TicketController::VerListaTicket

DetalleTicket:
              path:     /CU02ConsultarTicket3/{id}
              controller: App\Controller\TicketController::VerDetalleTicket

CU04DerivarTicket:
              path:     /CU04DerivarTicket
              controller: App\Controller\TicketController::VistaDerivarTicket
              methods: [POST]

CU04ProcesarDerivar:
              path:     /CU04ProcesarDerivar
              controller: App\Controller\TicketController::DerivarTicket

CU03CerrarTicket:
              path:     /CU03CerrarTicket
              controller: App\Controller\TicketController::CerrarTicket


CU20AgruparPorTicket:
              path:     /CU20AgruparPorTicket
              controller: App\Controller\TicketController::VerListaTicket

CU21AgruparPorLegajo:
              path:     /CU21AgruparPorLegajo
              controller: App\Controller\TicketController::VerListaTicket

CU22AgruparPorEstado:
              path:     /CU22AgruparPorEstado
              controller: App\Controller\TicketController::VerListaTicket

CU23AgruparPorUltimoGrupo:
              path:     /CU23AgruparPorUltimoGrupo
              controller: App\Controller\TicketController::VerListaTicket

CU24AgruparPorClasificacionTicket:
              path:     /CU24AgruparPorClasificacionTicket
              controller: App\Controller\TicketController::VerListaTicket

#---------------------------------------------------------------------------------------------------------------------#
#------RUTAS PARA LOS GRUPOS DE RESOLUCION----#
#---------------------------------------------------------------------------------------------------------------------#

ConsultarIntervenciones:
    path:       /CU07ConsultarIntervenciones
    controller: App\Controller\IntervencionController::VistaConsulta

ProcesaConsultaIntervenciones:
    path:       /CU07ProcesaIntervenciones
    controller: App\Controller\IntervencionController::ProcesarConsulta

ActualizarIntervencion:
    path:       /CU08ActualizarIntervencion/{id}
    controller: App\Controller\IntervencionController::VistaActualizar

ProcesarActualizacion:
    path:       /CU08ProcesarActualizacion
    controller: App\Controller\IntervencionController::Actualizar

RegistrarClasificacionDeTickets:
    path:      /CU10RegistrarClasificacionDeTickets
    controller: App\Controller\HomeController::index


BuscarClasifTicketsParte1:
    path:       /CU11BuscarClasifTicketsParte1
    controller: App\Controller\HomeController::index


