<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerClZKLd5\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerClZKLd5/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerClZKLd5.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerClZKLd5\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerClZKLd5\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ClZKLd5',
    'container.build_id' => 'f1a20118',
    'container.build_time' => 1586724245,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerClZKLd5');
